export enum PurchaseRequisitionStatus {
  INITIALIZED = "INITIALIZED",
  SAVED_FOR_LATER = "SAVED_FOR_LATER",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REQUEST_MODIFICATION = "REQUEST_MODIFICATION",
}
